name: SonarCloud Scan

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: SonarCloud
      uses: highbyte/sonarscan-dotnet@2.0
      with:
        # The key of the SonarQube project
        sonarProjectKey: PauloHMattos_Compiler
        # The name of the SonarQube project
        sonarProjectName: Compiler
        # The name of the SonarQube organization
        sonarOrganization: paulohmattos
        # Optional command arguments to dotnet test
        dotnetTestArguments: /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
        # Optional extra command arguments the the SonarScanner 'begin' command
        sonarBeginArguments: /d:sonar.verbose="true" /d:sonar.language="cs" /d:sonar.cs.opencover.reportsPaths="**/*opencover.xml"
        # The SonarQube server URL. For SonarCloud, don't set this setting.
        #sonarHostname: # optional, default is https://sonarcloud.io

    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
